Repository humanmade/altis-cloud, pull requests merged in 2020-08, with the labels that each got.

#226 Update build container package versions
  docs/build-scripts.md
Labels: backport v1-branch, backport v2-branch, backport v3-branch, backport v4-branch

#232 Check ELASTICSEARCH_HOST definition before use
  inc/namespace.php
Labels: backport v3-branch

#240 Allow use of alternate domain name for S3 on local
  inc/namespace.php
Labels: backport v4-branch
