Repository humanmade/altis-cloud, pull requests merged in 2020-03, with the labels that each got.

#153 Fix error logger to CloudWatch
  inc/cloudwatch_error_handler/namespace.php
Labels: backport v1-branch, backport v2-branch, backport v3-branch

#150 Update AWS X-Ray to 1.2.5
  composer.json
Labels: backport v3-branch, bug

#161 Update XRay to track patch version
  composer.json
Labels: backport v3-branch
