Repository humanmade/altis-cloud, pull requests merged in 2021-03, with the labels that each got.

#334 Only use APCU if loaded
  inc/namespace.php
Labels: backport v4-branch

#340 Cache uploads directories by blog ID
  inc/namespace.php
Labels: backport v4-branch, backport v5-branch, backport v6-branch

#344 Update minimum S3 Uploads version
  composer.json
Labels: backport v4-branch, backport v5-branch
