Repository humanmade/altis-cloud, pull requests merged in 2021-04, with the labels that each got.

#353 Update S3 Uploads to 3.0.0 Beta 1
  composer.json
Labels: backport v7-branch

#355 Update Batcache to latest version
  composer.json
Labels: backport v5-branch, backport v6-branch, backport v7-branch

#361 Dont append port number for 80 or 443
  inc/namespace.php
Labels: backport v4-branch, backport v5-branch, backport v6-branch, backport v7-branch

#362 Fix redis healthcheck
  inc/healthcheck/namespace.php
  inc/namespace.php
Labels: backport v4-branch, backport v5-branch, backport v6-branch, backport v7-branch

#372 Update S3 Uploads to 3.0.0 stable
  composer.json
Labels: backport v7-branch

#374 Truncate SES message data to CloudWatch
  inc/ses_to_cloudwatch/namespace.php
Labels: backport v4-branch, backport v5-branch, backport v6-branch, backport v7-branch

#380 Use clear scheduled hook to remove package status check
  inc/elasticsearch_packages/namespace.php
Labels: backport v5-branch, backport v6-branch, backport v7-branch

#384 Fix linter errors
  assets/environment-indicator.css
  inc/class-db.php
  inc/elasticsearch_packages/namespace.php
  inc/page_cache/namespace.php
Labels: backport v7-branch
