Repository humanmade/altis-cloud, pull requests merged in 2022-01, with the labels that each got.

#539 Correction to the configuration documentation
  docs/page-caching.md
Labels: backport v9-branch

#530 Refresh X-Ray docs for timeline view
  docs/assets/xray-database.png
  docs/assets/xray-errors.png
  docs/assets/xray-flamegraph.png
  docs/assets/xray-overview.png
  docs/assets/xray-remote-requests.png
  docs/assets/xray-request.png
  docs/assets/xray-timeline.png
  docs/dashboard/x-ray.md
Labels: backport v10-branch

#549 Update Ludicrous DB to 5.0.1
  composer.json
Labels: backport v6-branch, backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch
